package dev.jobhunter.people.model.enums;

public enum EventType {
    CONTACT_DISCOVERED, MESSAGE_SENT, REPLIED, CALL_BOOKED, REFERRAL_REQUESTED, REFERRAL_GIVEN, INTERVIEW_OBTAINED, GHOSTED_AUTO, STATUS_OVERRIDE
}
